apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: argo-service-app/order
    repoURL: https://github.com/zakkytaufiqurrohman/simple-app-k8s-manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}